version: "3.3"
services:
  omc:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
    container_name: omc-container
    # environment:
    volumes:
      - app:/app
    ports:
      - 7777:80
    restart: unless-stopped
volumes:
  app: {}

