version: "3.3"
services:
  omc:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
    container_name: omc-container
    command: uvicorn main:app --host 0.0.0.0
    # environment:
    volumes:
      - app:/app
    ports:
      - 7777:80
    restart: unless-stopped
volumes:
  app:
    external: true



# sudo docker run -d -p 7777:80 -v omc_app:/app --name omc-container omc-image